<!DOCTYPE html>

<html>

<head>

	<meta charset="UTF-8" />
	
	<title>(1) お兄ちゃん！</title>
	
	<link rel="stylesheet" href="./template01.css" />
	
</head>

<body>

	<div id="header">
		<div id="title">Free brain lavage</div>
		<div id="describ">俺の妹がこんなにダンデレわけがない！</div>
	</div>
	<div id="navbar">
		<span class="navbar"><a href="#">かわいい！</a></span>
		<span class="navbar"><a href="#">デス！</a></span>
		<span class="navbar"><a href="#">お兄ちゃん！</a></span>
	</div>
	
	<div id="inner">
	
		<div class="blok">
			<pre>............HIIMHIMHMMHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:.............
...........MMMI:MII:MIHMHMMMMMHMMMMIMMMIMMMMMMMMMMMMMM.............
.........:MMMI:M::HM::MIHHHM:IM:MHM:IMH:IMMMIIMMMHMMMH:............
........:MMMHHM::MMI:HH:MM:I:M:MMMH:IMH:IMM::MH:MM:MM:M............
.......MMMMHMM:MMIMHMII:MM:IIIM:MHMIMMM:MMIIH::MH:HM:M.............
...... :MIMMMMMMMMMHMMHMM:HHMHMMMMIMHMMMMHMHMIHIHM::MMI............
.......M:MMMMMMMMMMMMHMMMMMMMMHMMMMMMMMMMHMMMHMMIMHMMMM:...........
.......HHMMMMMMMMMMMMMMMMIMMMM.MMHMMMMHMMMMMMMMMMMIMHMMI...........
........MMMIMMMMMMMMMMIHMIMIM:.M:HMM:MIHMMMMMMMMMMMMMMMI...........
........MM.MMMMMMMMMMMH:MMMHM:.M.:MM.M.HMMMHMMMMMMMMMMMI...........
........MM.MMMMMMMMMMH::M.M.M..M..MM:M.IIMH:MMMMMMMMMMMI...........
........M:.MM:MMMMMMM:.I..:.I..H..IM:I.I.M.IMHMMMMMMMMMI...........
........M..MMMHMMMMM.:HI:HHH......H....II..:MMMMMMMHMM:............
...........MM.MIMMMM.:H: .::I........ ...:IH:.MMMMMM:MMI...........
...........:H..MMMIM.M.:...:I.........: ..::HHHMMMMIMMMH...........
............H..IMM:I:..I:..:..........I:..:I:::MMMMMMMMM...........
...............MMH::I...I:::..........III.I::MMMHMMMMMMM...........
..............MMMHMII.. ..............:MI:I.HIIIHM:HMMMM...........
.............:MMMMIM::...........:......:H..:II:MHIMMMMM...........
.............MMMMMMMMM......................I.MMMHHMMMMM:..........
............MMMMH:MMMMM........:.:.........:MMMMMMMMMMMMI..........
...........MMMMMMHMMMMMMM.. .............:MMMMMMMMMMMMMMM..........
........ .IMMMMMMMMMMMMMMMM............:MMMMMMMMMHMMMMMMM..........
..........MMMMMMMMMMMMMMMMMI:.......:IHMMMMMMMMM::MMMMMMM..........
.........MMMMMMMIMMMMMMMMMMH:::I:I:.::HMMMMMMMMMHMMMMMMMMI.........
........HMMMMMMM:MMMMMMMMMMI:::::::..:HMMMMMMMMIMMMMMMMMMM.........
.......IMMMMM..MI:MMMMMMMMM::::..:::::.MMMMMMMMMMMMMMMMMMM ........
......:MMMM....:MMHMMMMMM:::::.....::.:.MMMMMMMHMMMMMMMMMM.........
......MMI....:::IMMMMI:.:::::.....:I::::::HMMMHIM::::::MMMH........
.....MM.....:::IMIMMM:.......:....::::::::IMMHMM:I:::I:::MM .......
....MMM.....:I:.MIHMMM........:...:::::::HMMMMI:::::....::M:.......
...:MM:........:MMMHMM..................IMMMMM::...........M.......
...MMM........:::MMMMM......:..........:HMMMMM::...................
..:MM:.......:::::MMMM........... .. .::MMM:HM::.............:.....
..MMM........:::::MMMMM:I..HHIMHMHHHM :IMMHIMH::.............I.....
</pre>
		</div>
	
		<div class="blok">
			<h1>お兄ちゃん！</h1>
			<p>大丈夫</p>
			<p>デス</p>
			<p>か？</p>
		</div>

	</div>
	
	<div id="footer">
		&copy; onee-chan, wallpapper by [original author], if it's you <a href="mailto:ax.fiolle@gmail.com">contact me</a><iframe width="1" height="1" src="//www.youtube.com/embed/H2AYO_K7E0M?autoplay=1" frameborder="0" allowfullscreen></iframe>
		<br>Was that the worst experience ever ? &hearts; you can now free your rage on <a href="../pointlessbutton">Pointless button</a>.
	</div>
	
	<script>
	onii = Math.floor((Math.random() * 10) + 1); 
	switch (onii)
	{
		case 1:
			alert("Onii-Chan !! <3");
			break;
		case 10:
			alert("Onii-chan ?? ;_;");
			break;
	}
	</script>
	<!-- Onii-Chan, suki dayo ! -->
</body>

</html>