website_micro_apps:
    resource: "@WebsiteMicroAppsBundle/Resources/config/routing.yml"
    prefix:   /

website_portfolio:
    resource: "@WebsitePortfolioBundle/Resources/config/routing.yml"
    prefix:   /