website_portfolio_homepage:
    path: /
    defaults: 
      _controller: WebsitePortfolioBundle:Default:index

website_portfolio_otherpage:
    path: /{page}
    defaults: 
      _controller: WebsitePortfolioBundle:Default:other