services:
    website_portfolio.mailer:
        class: Website\PortfolioBundle\Services\WebsitePortfolioMailer
        arguments: 
            - "@mailer"
            - "%name%"
            - "%from%"
            - "%msg%"
